CREATE TABLE USERS (
    U_ID NUMBER PRIMARY KEY,
    ID VARCHAR2(255),
    PASSWORD VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    EMAIL VARCHAR2(255),
    NUM NUMBER,
    ROLE VARCHAR2(50) DEFAULT 'ROLE_USER' NOT NULL
);

CREATE TABLE BOOK (
    B_ID NUMBER PRIMARY KEY,
    NUM NUMBER,
    PIC VARCHAR2(255),
    TITLE VARCHAR2(255),
    AUTHOR VARCHAR2(255),
    PRICE NUMBER,
    INFO CLOB,
    CATEGORY VARCHAR2(255)
);

CREATE TABLE BAG (
    U_ID NUMBER,
    B_ID NUMBER,
    QUANTITY NUMBER,
    PRIMARY KEY (U_ID, B_ID),
    FOREIGN KEY (U_ID) REFERENCES USERS(U_ID),
    FOREIGN KEY (B_ID) REFERENCES BOOK(B_ID)
);

CREATE TABLE COMMENTS (
    ID NUMBER PRIMARY KEY,
    B_ID NUMBER NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    CONTENT CLOB NOT NULL,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SCORE NUMBER(1,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_BOOK FOREIGN KEY (B_ID)
        REFERENCES BOOK(B_ID)
        ON DELETE CASCADE
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    U_ID VARCHAR2(255),
    NAME VARCHAR2(255),
    NUM VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    POST VARCHAR2(50),
    DETAIL_ADDRESS VARCHAR2(255)
);

CREATE TABLE PAYMENT_ITEMS (
    PAYMENT_ITEM_ID NUMBER PRIMARY KEY,
    PAYMENT_ID NUMBER,
    TITLE VARCHAR2(255),
    QUANTITY NUMBER,
    PRICE NUMBER,
    SALE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PAYMENT FOREIGN KEY (PAYMENT_ID)
        REFERENCES PAYMENTS(PAYMENT_ID)
        ON DELETE CASCADE
);
